[Writable]
LogLevel = "INFO"

[Service]
Port = 59910
StartupMsg = "device gpio started"

[MessageBus]
  [MessageBus.Optional]
  # Default MQTT & NATS Specific options that need to be here to enable environment variable overrides of them
  ClientId = "device-gpio"

[Driver]
Interface = "sysfs"
# Interface = "chardev"  # this interface is experimental
ChipSelected = "0"
