Writable:
  LogLevel : "INFO"
  
Service:
  Host: localhost
  Port : 59910
  StartupMsg : "device gpio started"

# uncomment when running from command-line in hybrid mode with -cp -o flags
# Clients:
#   core-metadata:
#     Host: "localhost"
# Registry:
#   Host: "localhost"

MessageBus:
  # Host: localhost # uncomment when running from command-line in hybrid mode
  Optional:
  # Default MQTT & NATS Specific options that need to be here to enable environment variable overrides of them
    ClientId : "device-gpio"

Driver:
  Interface : "sysfs"
  # Interface : "chardev"  # this interface is experimental
  ChipSelected : "0"

Device:
  # These have common values (currently), but must be here for service local env overrides to apply when customized
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"
